version: '3.1'
services :
  postgres:
    image: postgres:10-alpine
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tododb
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000
